#! /bin/sh

# Start up processes

sudo auto-cpufreq --live &
sudo libvirtd -d &
sudo virtlogd -d &
$HOME/.config/polybar/launch.sh &
discord &

pgrep -x sxhkd > /dev/null || sxhkd &

# BSPWM config

bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width         2
bspc config window_gap           5

bspc config normal_border_color "#eceff4"
bspc config focused_border_color "#81A1C1"

bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false

bspc rule -a discord desktop='^2' state=tiling follow=on
bspc rule -a Spotify desktop='^4' state=tiling follow=on
#bspc rule -a firefox desktop='^1' state=tiling follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
